services:
  controller:
    build: ./controller
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DATABASE_PATH=/app/data/deploybot.db
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET:-your-webhook-secret-here}
      - LOG_LEVEL=INFO
    volumes:
      - ./controller/data:/app/data
      - ./controller/config:/app/config
      - ./controller/ui:/app/ui
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  agent:
    build: ./agent
    user: "0:0"
    environment:
      - CONTROLLER_URL=http://controller:8080
      - AGENT_TOKEN=${AGENT_TOKEN:-dev-token}
      - ALLOW_INSECURE_CONTROLLER=true
      - AGENT_DATA_DIR=/var/lib/deploybot
      - AGENT_WORK_DIR=/work
      - HEARTBEAT_INTERVAL=30s
    volumes:
      - ./agent/data:/var/lib/deploybot
      - ./agent/work:/work
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - controller
    restart: unless-stopped
